name: generate metrics dashboard

on:
  schedule:
    - cron: "0 */8 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # main classic dashboard
  classic:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: assets/metrics.svg
          token: ${{ github.token }}
          user: DWGX
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          config_padding: 0, 8px
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics dashboard"

